from sqlalchemy import Column, Integer, Boolean, String, ForeignKey, JSON, DateTime, Float
from sqlalchemy.orm import relationship

from wb_invest_stat.ozon.DB import connect_db

from wb_invest_stat.ozon.DB.models.companies import Company


class ProductInfo(connect_db.Base):
    __tablename__ = 'product_info'

    product_id = Column(Integer, primary_key=True, autoincrement=False, nullable=False)
    client_id = Column(Integer, ForeignKey('companies.client_id'), nullable=False, index=True)
    name = Column(String, nullable=True)
    offer_id = Column(String, nullable=True)
    barcode = Column(String, nullable=True)
    created_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, nullable=True)
    images = Column(JSON, nullable=True)
    marketing_price = Column(Float, nullable=True)
    old_price = Column(Float, nullable=True)
    premium_price = Column(Float, nullable=True)
    price = Column(Float, nullable=True)
    recommended_price = Column(Float, nullable=True)
    min_price = Column(Float, nullable=True)
    sources_fbo_sku = Column(Integer, nullable=True)
    sources_fbs_sku = Column(String, nullable=True)
    stocks_coming = Column(Integer, nullable=True)
    stocks_present = Column(Integer, nullable=True)
    stocks_reserved = Column(Integer, nullable=True)
    errors = Column(JSON, nullable=True)
    vat = Column(Float, nullable=True)
    visible = Column(Boolean, nullable=True)
    visibility_details_has_price = Column(Boolean, nullable=True)
    visibility_details_has_stock = Column(Boolean, nullable=True)
    visibility_details_active_product = Column(Boolean, nullable=True)
    volume_weight = Column(Float, nullable=True)
    is_prepayment = Column(Boolean, nullable=True)
    is_prepayment_allowed = Column(Boolean, nullable=True)
    images360 = Column(JSON, nullable=True)
    color_image = Column(String, nullable=True)
    primary_image = Column(String, nullable=True)
    status = Column(String, nullable=True)
    status_state_name = Column(String, nullable=True)
    status_state_description = Column(String, nullable=True)
    status_state_tooltip = Column(String, nullable=True)
    item_errors_description = Column(String, nullable=True)
    item_errors_matched_offer_id = Column(String, nullable=True)
    moderate_status = Column(String, nullable=True)
    state = Column(String, nullable=True)
    currency_code = Column(String, nullable=True)
    is_kgt = Column(Boolean, nullable=True)
    discounted_stocks_coming = Column(Integer, nullable=True)
    discounted_stocks_present = Column(Integer, nullable=True)
    discounted_stocks_reserved = Column(Integer, nullable=True)
    is_discounted = Column(Boolean, nullable=True)
    has_discounted_item = Column(Boolean, nullable=True)
    barcodes = Column(JSON, nullable=True)
    price_index = Column(String, nullable=True)
    external_price_min_price = Column(String, nullable=True)
    external_price_index_value = Column(Float, nullable=True)
    ozon_price_min_price = Column(String, nullable=True)
    ozon_price_index_value = Column(Float, nullable=True)
    marketplaces_price_min_price = Column(String, nullable=True)
    marketplaces_price_index_value = Column(Float, nullable=True)
    sku = Column(Integer, nullable=True)
    description_category_id = Column(Integer, nullable=True)

    client = relationship("Company", foreign_keys=[client_id])
